# Configuration Développement
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./data/deliverydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # Désactive Spring AI en dev si pas de clé API
  ai:
    openai:
      enabled: false

app:
  optimizer:
    active: nearest_neighbor

logging:
  level:
    com.delivery: DEBUG
    org.hibernate.SQL: DEBUG